from supabase import create_client, Client
from app.config import settings
from datetime import datetime, timedelta
import pytz

# Initialize Supabase client
supabase: Client = create_client(settings.SUPABASE_URL, settings.SUPABASE_KEY)

def fetch_user_profile(user_id: int) -> dict:
    """
    Fetch the user's gender, weight and daily goal.
    """
    user_res = supabase.table("users").select("gender, weight").eq("user_id", user_id).execute()
    user_data = user_res.data[0] if user_res.data else {}
    
    goal_res = supabase.table("goals").select("daily_target").eq("user_id", user_id).execute()
    goal_data = goal_res.data[0] if goal_res.data else {}

    return {
        "gender": user_data.get("gender", "未知"), 
        "weight": user_data.get("weight", 60),
        "goal_ml": goal_data.get("daily_target", 2000)
    }

def fetch_recent_water_records(user_id: int, limit: int = 10) -> list:
    """
    Fetch the latest 'limit' number of drinking logs for the timeline context.
    """
    logs_res = supabase.table("drinking_logs").select("d_volume, record_at").eq("user_id", user_id).order("record_at", desc=True).limit(limit).execute()
    return logs_res.data if logs_res.data else []

def fetch_today_water_sum(user_id: int) -> int:
    """
    Calculate the total water intake for 'today' (anchored to the latest DB record).
    """
    logs_res = supabase.table("drinking_logs").select("record_at").eq("user_id", user_id).order("record_at", desc=True).limit(1).execute()
    
    if logs_res.data:
        latest_time_str = logs_res.data[0]['record_at']
        now = datetime.fromisoformat(latest_time_str.replace('Z', '+00:00')).astimezone(pytz.timezone('Asia/Taipei'))
    else:
        now = datetime.now(pytz.timezone('Asia/Taipei'))

    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    today_logs_res = supabase.table("drinking_logs").select("d_volume").eq("user_id", user_id).gte("record_at", today_start.isoformat()).lte("record_at", now.isoformat()).execute()
    return sum([log.get("d_volume", 0) for log in today_logs_res.data]) if today_logs_res.data else 0

def fetch_weekly_water_sum(user_id: int) -> dict:
    """
    Calculate the sum of water intake for the past 7 days, grouped by day.
    """
    latest_log_res = supabase.table("drinking_logs").select("record_at").eq("user_id", user_id).order("record_at", desc=True).limit(1).execute()
    
    if latest_log_res.data:
        latest_time_str = latest_log_res.data[0]['record_at']
        now = datetime.fromisoformat(latest_time_str.replace('Z', '+00:00')).astimezone(pytz.timezone('Asia/Taipei'))
    else:
        now = datetime.now(pytz.timezone('Asia/Taipei'))
        
    seven_days_ago = now - timedelta(days=7)
    
    logs_res = supabase.table("drinking_logs").select("d_volume, record_at").eq("user_id", user_id).gte("record_at", seven_days_ago.isoformat()).lte("record_at", now.isoformat()).execute()
    
    weekly_stats = { (now - timedelta(days=i)).strftime("%Y-%m-%d"): 0 for i in range(7) }
    
    for log in logs_res.data:
        try:
            record_time = datetime.fromisoformat(log['record_at'].replace('Z', '+00:00'))
            local_time = record_time.astimezone(pytz.timezone('Asia/Taipei'))
            date_str = local_time.strftime("%Y-%m-%d")
            if date_str in weekly_stats:
                weekly_stats[date_str] += log.get("d_volume", 0)
        except Exception as e:
            pass
            
    sorted_dates = sorted(weekly_stats.keys())
    # Return mapping for mon, tue, wed... for prompt compatibility
    return {
        "mon_ml": weekly_stats.get(sorted_dates[0], 0),
        "tue_ml": weekly_stats.get(sorted_dates[1], 0),
        "wed_ml": weekly_stats.get(sorted_dates[2], 0),
        "thu_ml": weekly_stats.get(sorted_dates[3], 0),
        "fri_ml": weekly_stats.get(sorted_dates[4], 0),
        "sat_ml": weekly_stats.get(sorted_dates[5], 0),
        "sun_ml": weekly_stats.get(sorted_dates[6], 0),
    }

def insert_sensor_log(data: dict) -> dict:
    """
    Insert a localized sensor log into the DB, replacing the memory array.
    """
    # Assuming drinkAmount was passed, we might need a type_id (using 1 as default for water)
    # This aligns the hardware mock data to the database schema
    new_record = {
        "user_id": data.get('user_id', 1), # Defaulting if missing
        "type_id": 1, 
        "d_volume": data.get('drinkAmount', 0),
        "is_auto": True
        # record_at is auto-generated by supabase usually, otherwise we pass it
    }
    
    if data.get('timestamp'):
        new_record['record_at'] = data.get('timestamp')
        
    if new_record["d_volume"] > 0:
        res = supabase.table("drinking_logs").insert(new_record).execute()
        return res.data[0] if res.data else None
    
    return None

